version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=production
    volumes:
      - .:/app:cached
    restart: unless-stopped
